### ISSUE TITLE
Acknowledgments

### ISSUE THREAD

**Issue by rochelleterman** [plsc-31101/00_Pre-class#9]
List of all unique contributors.

**Comment by GiacomoRamos** [comment]
Repos I've checked:

- [ ] 0

- [ ] 1

- [ ] 2

- [ ] 3

- [ ] 4

- [ ] 5

- [ ] 6

- [ ] 7

- [ ] 8

- [ ] 9

- [ ] 10

- [ ] 11

- [ ] 12

- [ ] 13

- [ ] 14

- [ ] 15

- [R for Data Science](https://r4ds.had.co.nz/).
- [Computing for Social Sciences](https://cfss.uchicago.edu).

**Comment by rochelleterman** [comment]
Please add these too (even if they're not in any repos:)
- [Justin Grimmer](https://www.justingrimmer.org/)
- [Stat545](https://stat545.com/)

**Comment by GiacomoRamos** [comment]
Done!

**Comment by rochelleterman** [comment]
Thanks!
